### ISSUE TITLE
Cannot connect to infinispan host running inside docker

### ISSUE THREAD

**Issue by arashbi** [jboss-dockerfiles/infinispan#31]
I am running this docker file. But I cannot to it.
My client configuration looks like 
```java
cb.tcpNoDelay(true)
                .connectionPool()
                .numTestsPerEvictionRun(3)
                .testOnBorrow(false)
                .testOnReturn(false)
                .testWhileIdle(true)
                .addServer()
                .host("localhost")
                .port(11222);
```
The stack trace looks like 
```
org.infinispan.client.hotrod.exceptions.TransportException: Could not connect to server: /172.17.0.4:11372
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransport.<init>(TcpTransport.java:78) ~[infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:37) ~[infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:16) ~[infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1748) ~[infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.updateTopologyInfo(TcpTransportFactory.java:356) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.updateServers(TcpTransportFactory.java:315) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readNewTopologyAndHash(Codec20.java:418) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readNewTopologyIfPresent(Codec20.java:379) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readPartialHeader(Codec20.java:125) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.protocol.Codec20.readHeader(Codec20.java:118) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.operations.HotRodOperation.readHeaderAndValidate(HotRodOperation.java:56) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.operations.PingOperation.execute(PingOperation.java:45) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.ping(TransportObjectFactory.java:52) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:45) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:16) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.pingServersIgnoreException(TcpTransportFactory.java:180) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.start(TcpTransportFactory.java:151) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.RemoteCacheManager.start(RemoteCacheManager.java:577) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.RemoteCacheManager.<init>(RemoteCacheManager.java:180) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at org.infinispan.client.hotrod.RemoteCacheManager.<init>(RemoteCacheManager.java:166) [infinispan-embedded-8.2.1.Final.jar:8.2.1.Final]
	at com.bibliocommons.cache.InfinispanCacheConfig.getInfinispanCacheManager(InfinispanCacheConfig.java:35) [main/:?]
	at com.bibliocommons.cache.InfinispanCacheConfig.getCacheManager(InfinispanCacheConfig.java:41) [main/:?]
```

To start with, I don't understand why the client has my docker files ip address instead of localhost I mentioned. In a remote machine, this is not going to work at all.
Second, why it fails? the port 11372 is exposed.

**Comment by gustavonalle** [comment]
The Infinispan server will send the list of the members of the cluster to the client, so that it can use this info to access entries directly where they are located. 

You should not need to expose ports in your docker container, but rather connect directly to the container via IP. Example, on Linux all containers are accessible:
```
$ docker run -d jboss/infinispan-server                                        
e68932d320770012b9082dc899f31145faf01f0df2c5043ffe48785643df2675
$ docker inspect --format '{{ .NetworkSettings.IPAddress }}' $(docker ps -q -l)
172.17.0.2
$ telnet 172.17.0.2 11222
Trying 172.17.0.2...
Connected to 172.17.0.2.
Escape character is '^]'.
```

The fact that you cannot reach the container might be an issue with your docker setup.

**Comment by gustavonalle** [comment]
Alternatively, you can use the ```external-host``` configuration in the Infinispan server:

```xml
...
<hotrod-connector name="hotrod1" socket-binding="hotrod" cache-container="default"  ...>
      <topology-state-transfer external-host="localhost"  ... />
</hotrod-connector>
...
```

For that you need to define your own customized xml config based on ```clustered.xml``` and mount it in the docker container. Suppose you have a ```custom-config.xml``` with the config above in the ```/local/path``` in your environment:

```
docker run -p 11222:11222 -v /local/path:/opt/jboss/infinispan-server/standalone/configuration/my-config -it jboss/infinispan-server  my-config/custom-config
```

This will mount the local folder to ```/opt/jboss/infinispan-server/standalone/configuration/my-config``` inside the container and will start the server with the ```custom-config.xml``` file in the mapped volume.

**Comment by arashbi** [comment]
How does the first options works remotely?  Should I setup a private network for dockers ?

**Comment by gustavonalle** [comment]
In order to work remotely, you'd need to use a different docker network (see [doc](https://docs.docker.com/engine/userguide/networking/)) for you container, either a custom one, or the ```host``` network:

```docker run --network=host -it jboss/infinispan-server -b <your_ip>```

where ```your_ip``` is the IP of you server visible outside
