### ISSUE TITLE
GossipRouter: JGRP000188: failed reading request

### ISSUE THREAD

**Issue by rpofuk** [jboss-dockerfiles/infinispan#68]
Running: 9.1.0.Final-2
Jgroup version: 3.6.13.Final

**INFINISPAN**:
docker run -p9990:9990 -it \
-eAPP_USER=admin \
-eAPP_PASS=admin \
-eMGMT_USER=admin \
-eMGMT_PASS=admin \
jboss/infinispan-server:9.1.0.Final \
-Djboss.default.jgroups.stack=tcp-gossip \
-Djgroups.gossip.initial_hosts=172.17.0.1[12001]

**JGROUPS**:
docker run -p 12001:12001 -e "LogLevel=TRACE" jboss/jgroups-gossip:3.6.12.Final

**ERROR ON JGROUPS**:
309388 [ERROR] GossipRouter: JGRP000188: failed reading request
java.lang.RuntimeException: class for magic number 0 not found
at org.jgroups.util.Util.readOtherAddress(Util.java:1194) ~[jgroups.jar:3.6.13.Final]
at org.jgroups.util.Util.readAddress(Util.java:1137) ~[jgroups.jar:3.6.13.Final]
at org.jgroups.protocols.PingData.readFrom(PingData.java:158) ~[jgroups.jar:3.6.13.Final]
at org.jgroups.stack.GossipData.readFrom(GossipData.java:171) ~[jgroups.jar:3.6.13.Final]
at org.jgroups.stack.GossipRouter.readRequest(GossipRouter.java:276) [jgroups.jar:3.6.13.Final]
at org.jgroups.stack.GossipRouter.receive(GossipRouter.java:231) [jgroups.jar:3.6.13.Final]
at org.jgroups.util.Util.bufferToArray(Util.java:798) [jgroups.jar:3.6.13.Final]
at org.jgroups.blocks.cs.ReceiverAdapter.receive(ReceiverAdapter.java:25) [jgroups.jar:3.6.13.Final]
at org.jgroups.blocks.cs.NioConnection._receive(NioConnection.java:239) [jgroups.jar:3.6.13.Final]
at org.jgroups.blocks.cs.NioConnection$Reader._run(NioConnection.java:454) [jgroups.jar:3.6.13.Final]
at org.jgroups.blocks.cs.NioConnection$Reader.run(NioConnection.java:443) [jgroups.jar:3.6.13.Final]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by gustavonalle** [comment]
Hi, Infinispan 9.1.0.Final-x uses JGroups 4 internally, which was missing from docker hub. Please try again with 

```
docker run -p 12001:12001 -e "LogLevel=TRACE" jboss/jgroups-gossip:4.0.0.Final
```

**Comment by gustavonalle** [comment]
Hi @rpofuk does using a different groups version solve the problem for you?

**Comment by gustavonalle** [comment]
Closing, please create another issue if the problem persists
